development:
  adapter: sqlite3
  encoding: unicode
  database: tmp/skyway_development.sqlite
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: tmp/skyway_test.sqlite
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: skyway_production
  pool: 5
